import "./globals.css";

import type { Metadata } from "next";
import { Toaster } from "sonner";

import { fontSans } from "@/lib/fonts";

import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Coolection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
