import "./globals.css";

import type { Metadata } from "next";
import { Toaster } from "sonner";

import { fontSans } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Coolection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
